buildVariable: true
category:
- SERIF
familyName: Noto Serif Kannada
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifKannada.glyphs
